# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 10:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import stemp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HeatProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=8760)),
            ],
            bases=(models.Model, stemp.models.ProfileMixin),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('load_demand', models.FloatField(verbose_name='Jährlicher Strombedarf')),
                ('heat_demand', models.FloatField(verbose_name='Jährlicher Wärmebedarf')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp.District')),
                ('heat_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp.HeatProfile')),
            ],
        ),
        migrations.CreateModel(
            name='LoadProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=8760)),
            ],
            bases=(models.Model, stemp.models.ProfileMixin),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp.Parameter')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stemp.Result')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp.Scenario')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp.Setup')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='load_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp.LoadProfile'),
        ),
    ]
