# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stemp", "0004_remove_household_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="districts",
            field=models.ManyToManyField(null=True, to="stemp.District"),
        ),
    ]
