# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemp', '0006_auto_20180301_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictHouseholds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp.District')),
            ],
        ),
        migrations.RemoveField(
            model_name='household',
            name='districts',
        ),
        migrations.AddField(
            model_name='districthouseholds',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp.Household'),
        ),
    ]
