# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stemp', '0008_household_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='simulation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
