# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stemp", "0009_auto_20180312_0844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stemp.Result"
            ),
        ),
    ]
