# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 12:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stemp", "0012_remove_simulation_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="result", name="data",),
        migrations.AddField(
            model_name="result",
            name="param_result",
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="result",
            name="result",
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
