# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-15 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stemp", "0013_auto_20180312_1338"),
    ]

    operations = [
        migrations.RemoveField(model_name="simulation", name="result",),
        migrations.AddField(
            model_name="simulation",
            name="result_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Result",),
    ]
