# Generated by Django 2.0.4 on 2018-04-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemp', '0015_simulation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_person', models.IntegerField()),
                ('question_household', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stemp.Household')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionHouseholds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp.Household')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp.Question')),
            ],
        ),
    ]
