# Generated by Django 2.0.4 on 2018-04-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp', '0016_question_questionhouseholds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionHouseholds',
            new_name='QuestionHousehold',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_household',
        ),
    ]
