# Generated by Django 2.0.4 on 2018-04-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemp', '0017_auto_20180412_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionhousehold',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionhousehold',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_household', to='stemp.Household'),
        ),
        migrations.AlterField(
            model_name='questionhousehold',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_household', to='stemp.Question'),
        ),
    ]
