# Generated by Django 2.0.4 on 2018-05-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stemp", "0018_auto_20180412_1002"),
    ]

    operations = [
        migrations.RemoveField(model_name="simulation", name="setup",),
        migrations.DeleteModel(name="Setup",),
    ]
