# Generated by Django 2.0.4 on 2018-05-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stemp", "0019_auto_20180508_1201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionhousehold",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_household",
                to="stemp.Household",
                unique=True,
            ),
        ),
    ]
