# Generated by Django 2.0.4 on 2018-05-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stemp", "0020_auto_20180514_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionhousehold",
            name="household",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_household",
                to="stemp.Household",
            ),
        ),
    ]
