# Generated by Django 2.0.4 on 2018-05-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp', '0022_auto_20180514_1616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('number_of_persons', 'at_home', 'renovated')},
        ),
    ]
