# Generated by Django 2.0.4 on 2018-05-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stemp", "0023_auto_20180514_1638"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="renovated", new_name="modernized",
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("number_of_persons", "at_home", "modernized")},
        ),
    ]
