# Generated by Django 2.0.4 on 2018-05-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp', '0025_auto_20180514_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='predefined',
        ),
    ]
