# Generated by Django 2.0.4 on 2018-07-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stemp", "0026_remove_household_predefined"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="question", unique_together=set(),),
        migrations.RemoveField(model_name="question", name="at_home",),
        migrations.RemoveField(model_name="question", name="modernized",),
    ]
