# Generated by Django 2.0.4 on 2018-07-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp', '0029_auto_20180709_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='load_demand',
        ),
        migrations.RemoveField(
            model_name='household',
            name='load_profile',
        ),
    ]
